// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRdX2TY_VmPzo78ThjlJykcUNVWXfMpio',
    appId: '1:674199425144:web:a74018a5e21cc318059d8d',
    messagingSenderId: '674199425144',
    projectId: 'magnum-posts',
    authDomain: 'magnum-posts.firebaseapp.com',
    storageBucket: 'magnum-posts.firebasestorage.app',
    measurementId: 'G-88FLL0N76R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtK_kNhp_o40ingHR8QE3S7lFNVBehgo',
    appId: '1:674199425144:android:1988a4a189dcc765059d8d',
    messagingSenderId: '674199425144',
    projectId: 'magnum-posts',
    storageBucket: 'magnum-posts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqzwFbf2B9gbwELBLhk6ja0lWC4zD6zM',
    appId: '1:674199425144:ios:e706eb66663a8a19059d8d',
    messagingSenderId: '674199425144',
    projectId: 'magnum-posts',
    storageBucket: 'magnum-posts.firebasestorage.app',
    iosBundleId: 'com.example.magnumPosts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqzwFbf2B9gbwELBLhk6ja0lWC4zD6zM',
    appId: '1:674199425144:ios:e706eb66663a8a19059d8d',
    messagingSenderId: '674199425144',
    projectId: 'magnum-posts',
    storageBucket: 'magnum-posts.firebasestorage.app',
    iosBundleId: 'com.example.magnumPosts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRdX2TY_VmPzo78ThjlJykcUNVWXfMpio',
    appId: '1:674199425144:web:c87f8bcd9f8997d4059d8d',
    messagingSenderId: '674199425144',
    projectId: 'magnum-posts',
    authDomain: 'magnum-posts.firebaseapp.com',
    storageBucket: 'magnum-posts.firebasestorage.app',
    measurementId: 'G-KVNNLZBHTD',
  );
}
